Script "BurstFireShotgunStartCooldown" (void)
{
	GiveInventory("BurstFireCooldown",25);
	TakeInventory("BurstFireActivated",1);
	
	ACS_NamedExecute("ShotgunUpgradeCooldown",0,0,0,0);
}

Script "ExplosiveShotgunStartCooldown" (void)
{
	GiveInventory("ExplosiveCooldown",50);
	TakeInventory("ExplosiveActivated",1);
	
	ACS_NamedExecute("ShotgunUpgradeCooldown",0,0,0,0);
}

Script "ShotgunUpgradeCooldown" (void)
{
	if(CheckInventory("BurstFireCooldown"))
	{
	Delay(25);
	TakeInventory("BurstFireCooldown",1);
	}

	if(CheckInventory("ExplosiveCooldown"))
	{
	delay(25);
	TakeInventory("ExplosiveCooldown",1);
	}
}

script "SSGFireUpgradeCheck" (void)
{
	if(CheckInventory("SSGDoubleTrouble"))
	{
	GiveInventory("SSGCounter",1);
	TakeInventory("Shell",1);
	}
	else
	{
	GiveInventory("SSGCounter",2);
	TakeInventory("Shell",2);
	}	
}

Script "GaussPreciseModeActive" (void)
{
	SetFont("");
//	HudMessage("a",0,0,0,0,0,0);
}

Script "NoUpgradedWeapons" (int Weapon)
{
	static str NoAltModeWeapon[6] = { "the Chainsaw", "the Energy Pistol", "the Repeater", "the Lightning Gun", "this thing...", "the STG-46" };
	
	If(CheckWeapon("64BrownFist"))
	{
	Print(s:"Go hit the gym."); delay(2);
	}
	else
	{
	Print(s:"UAC Modpacks do not apply to ", s:NoAltModeWeapon[Weapon-1]); delay(2);
	}
}

Script "NuDoomUnmakerChecker" (void)
{
	for(int i = 6666; i < 6766; i++)
	{
		if(CheckActorInventory(i,"D4Unmaker"))	//checks if you have unmaker or ruiner
		{
			SetResultValue(2);
			if(CheckActorInventory(i,"WpnPower1Icon") && CheckActorInventory(i,"WpnPower2Icon") && CheckActorInventory(i,"WpnPower3Icon"))	//checks if you have all 3 demon keys
			{
			SetResultValue(3);
			}
		}
	}
}